# -*- coding: utf-8 -*-
"""Generated by ArcGIS ModelBuilder on: 2019-09-10 09:23:13
All ModelBuilder functionality may not be exported. Edits may be required for equivalency with the original model.
"""

import arcpy

# To allow overwriting the outputs change the overwrite option to true.
arcpy.env.overwriteOutput = False

# Local variables:
PCA_Photos__2_ = "PCA Photos"
PCA_Photos = PCA_Photos__2_
Count = ""

# Process: Select Layer By Attribute
arcpy.SelectLayerByAttribute_management(in_layer_or_view=PCA_Photos__2_, selection_type="NEW_SELECTION", where_clause="created_date >= timestamp '2019-09-10 09:22:35'", invert_where_clause="")

