# -*- coding: utf-8 -*-
"""Generated by ArcGIS ModelBuilder on: 2019-08-29 09:38:10
All ModelBuilder functionality may not be exported. Edits may be required for equivalency with the original model.
"""

import arcpy

# To allow overwriting the outputs change the overwrite option to true.
arcpy.env.overwriteOutput = False

# Script parameters
Paver_Condition_Assessment_WFS = arcpy.GetParameterAsText(0) or r"PCA_Collector_WFS\Paver Condition Assessment WFS"
PAVERS_PCA = arcpy.GetParameterAsText(1) or r"C:\Users\temp\PCA_DATA.gdb\PAVERS_PCA"
# Local variables:
Paver_Condition_Assessment__2_ = Paver_Condition_Assessment_WFS
Paver_Condition_Assessment__3_ = Paver_Condition_Assessment__2_
MPA_gdb = r"C:\Users\dstarr\Documents\ArcGIS\Projects\MPA\MPA.gdb"
Output_Feature_Class = ""

# Process: Append
arcpy.Append_management(inputs=r"'PCA_Collector_WFS\Paver Condition Assessment WFS'", target=PAVERS_PCA, schema_type="TEST", field_mapping="", subtype="", expression="")

# Process: Calculate Field (4)
arcpy.CalculateField_management(in_table=Paver_Condition_Assessment__2_, field="CONDITION", expression="MinimumValue( !PAVERS_OVERALL!, !PAVERS_PATCHES!, !PAVERS_PUMPING!, !PAVERS_RUTTING!, !PAVERS_JOINT_MATERIAL!)", expression_type="PYTHON_9.3", code_block="def MinimumValue(*args):
    return min(args)")

# Process: Feature Class to Feature Class
arcpy.FeatureClassToFeatureClass_conversion(in_features="", out_path=MPA_gdb, out_name="", where_clause="", field_mapping="", config_keyword="")

