# -*- coding: utf-8 -*-
"""Generated by ArcGIS ModelBuilder on: 2019-09-06 09:01:29
All ModelBuilder functionality may not be exported. Edits may be required for equivalency with the original model.
"""

import arcpy

# To allow overwriting the outputs change the overwrite option to true.
arcpy.env.overwriteOutput = False

# Script parameters
OTHER_PCA = arcpy.GetParameterAsText(0) or r"C:\Users\temp\PCA_DATA.gdb\OTHER_PCA"
PAVERS_PCA = arcpy.GetParameterAsText(1) or r"C:\Users\temp\PCA_DATA.gdb\PAVERS_PCA"
CONCRETE_PCA = arcpy.GetParameterAsText(2) or r"C:\Users\temp\PCA_DATA.gdb\CONCRETE_PCA"
ASPHALT_PCA = arcpy.GetParameterAsText(3) or r"C:\Users\temp\PCA_DATA.gdb\ASPHALT_PCA"
Paver_Condition_Assessment_WFS = arcpy.GetParameterAsText(4) or r"PCA_Collector_WFS\Paver Condition Assessment WFS"
Concrete_Pavement_Condition_Assessment_WFS = arcpy.GetParameterAsText(5) or r"PCA_Collector_WFS\Concrete Pavement Condition Assessment WFS"
Asphalt_Pavement_Condition_Assessment_WFS = arcpy.GetParameterAsText(6) or r"PCA_Collector_WFS\Asphalt Pavement Condition Assessment WFS"
Other_Type_of_Pavement_Condition_Assessment_WFS = arcpy.GetParameterAsText(7) or r"PCA_Collector_WFS\Other Type of Pavement Condition Assessment WFS"
OTHER_PCA_Updates = arcpy.GetParameterAsText(8) or r"C:\Users\temp\PCA_DATA.gdb\OTHER_PCA_Updates"
# Local variables:
Updated_Input_With_Rows_Removed = OTHER_PCA
Updated_Input_With_Rows_Removed__2_ = PAVERS_PCA
Updated_Input_With_Rows_Removed__3_ = CONCRETE_PCA
Updated_Input_With_Rows_Removed__4_ = ASPHALT_PCA
ASPHALT_PCA_Updates = r"C:\Users\temp\PCA_DATA.gdb\ASPHALT_PCA_Updates"
Delete_Succeeded = "true"
CONCRETE_PCA_Updates = r"C:\Users\temp\PCA_DATA.gdb\CONCRETE_PCA_Updates"
Delete_Succeeded__2_ = "true"
PAVERS_PCA_Updates = r"C:\Users\temp\PCA_DATA.gdb\PAVERS_PCA_Updates"
Delete_Succeeded__3_ = "true"
Other_Type_of_Pavement_Condition_Assessment__2_ = Paver_Condition_Assessment_WFS
Other_Type_of_Pavement_Condition_Assessment__4_ = Concrete_Pavement_Condition_Assessment_WFS
Other_Type_of_Pavement_Condition_Assessment__5_ = Asphalt_Pavement_Condition_Assessment_WFS
Asphalt_Pavement_Condition_Assessment_WFS__3_ = Other_Type_of_Pavement_Condition_Assessment_WFS
Delete_Succeeded__4_ = "true"

# Process: Delete Rows
arcpy.DeleteRows_management(in_rows=OTHER_PCA)

# Process: Delete Rows (2)
arcpy.DeleteRows_management(in_rows=PAVERS_PCA)

# Process: Delete Rows (3)
arcpy.DeleteRows_management(in_rows=CONCRETE_PCA)

# Process: Delete Rows (4)
arcpy.DeleteRows_management(in_rows=ASPHALT_PCA)

# Process: Delete
arcpy.Delete_management(in_data=r"C:\Users\temp\PCA_DATA.gdb\ASPHALT_PCA_Updates", data_type="")

# Process: Delete (2)
arcpy.Delete_management(in_data=r"C:\Users\temp\PCA_DATA.gdb\CONCRETE_PCA_Updates", data_type="")

# Process: Delete (3)
arcpy.Delete_management(in_data=r"C:\Users\temp\PCA_DATA.gdb\PAVERS_PCA_Updates", data_type="")

# Process: Delete Rows (5)
arcpy.DeleteRows_management(in_rows=Paver_Condition_Assessment_WFS)

# Process: Delete Rows (6)
arcpy.DeleteRows_management(in_rows=Concrete_Pavement_Condition_Assessment_WFS)

# Process: Delete Rows (7)
arcpy.DeleteRows_management(in_rows=Asphalt_Pavement_Condition_Assessment_WFS)

# Process: Delete Rows (8)
arcpy.DeleteRows_management(in_rows=Other_Type_of_Pavement_Condition_Assessment_WFS)

# Process: Delete (4)
arcpy.Delete_management(in_data=r"C:\Users\temp\PCA_DATA.gdb\OTHER_PCA_Updates", data_type="")

