# -*- coding: utf-8 -*-
"""Generated by ArcGIS ModelBuilder on: 2019-08-29 10:47:14
All ModelBuilder functionality may not be exported. Edits may be required for equivalency with the original model.
"""

import arcpy

# To allow overwriting the outputs change the overwrite option to true.
arcpy.env.overwriteOutput = False

# Script parameters
MPA_USER_PCA_POLYGONS = arcpy.GetParameterAsText(0) or r"C:\Users\dstarr\OneDrive - Johnson, Mirmiran & Thompson\Projects\MDOT MPA\Python tool\DODB12(1).sde\MPA_USER.PCA_POLYGONS"
ASPHALT_PCA = arcpy.GetParameterAsText(1) or r"C:\Users\temp\PCA_DATA.gdb\ASPHALT_PCA"
CONCRETE_PCA = arcpy.GetParameterAsText(2) or r"C:\Users\temp\PCA_DATA.gdb\CONCRETE_PCA"
PAVERS_PCA = arcpy.GetParameterAsText(3) or r"C:\Users\temp\PCA_DATA.gdb\PAVERS_PCA"
OTHER_PCA = arcpy.GetParameterAsText(4) or r"C:\Users\temp\PCA_DATA.gdb\OTHER_PCA"
# Local variables:
PAVERS_PCA_Updates = r"C:\Users\temp\PCA_DATA.gdb\PAVERS_PCA_Updates"
CONCRETE_PCA_Updates = r"C:\Users\temp\PCA_DATA.gdb\CONCRETE_PCA_Updates"
ASPHALT_PCA_Updates = r"C:\Users\temp\PCA_DATA.gdb\ASPHALT_PCA_Updates"
OTHER_PCA_Updates = r"C:\Users\temp\PCA_DATA.gdb\OTHER_PCA_Updates"

'C:\Users\dstarr\Documents\ArcGIS\Projects\MPA\MPA_USER@DODB12_1 - Copy.sde/MPA_USER.Pavement/PCA_POLYGONS' #;C:\Users\dstarr\Downloads\Pavement Assessments (MPA Version)\Pavement Assessments (MPA Version)\Default.gdb/PAVERS_PCA #
arcpy.Intersect_analysis(in_features=r"'C:\Users\dstarr\OneDrive - Johnson, Mirmiran & Thompson\Projects\MDOT MPA\Python tool\DODB12(1).sde\MPA_USER.PCA_POLYGONS' #;C:\Users\temp\PCA_DATA.gdb\PAVERS_PCA #", out_feature_class=PAVERS_PCA_Updates, join_attributes="ALL", cluster_tolerance="", output_type="INPUT")
'C:\Users\dstarr\Documents\ArcGIS\Projects\MPA\MPA_USER@DODB12 (2).sde\MPA_USER.PCA_POLYGONS'#;PAVERS_PCA#
# Process: Intersect (2)
arcpy.Intersect_analysis(in_features=r"'C:\Users\dstarr\OneDrive - Johnson, Mirmiran & Thompson\Projects\MDOT MPA\Python tool\DODB12(1).sde\MPA_USER.PCA_POLYGONS' #;C:\Users\temp\PCA_DATA.gdb\CONCRETE_PCA #", out_feature_class=CONCRETE_PCA_Updates, join_attributes="ALL", cluster_tolerance="", output_type="INPUT")

# Process: Intersect (3)
arcpy.Intersect_analysis(in_features=r"'C:\Users\dstarr\OneDrive - Johnson, Mirmiran & Thompson\Projects\MDOT MPA\Python tool\DODB12(1).sde\MPA_USER.PCA_POLYGONS' #;C:\Users\temp\PCA_DATA.gdb\ASPHALT_PCA #", out_feature_class=ASPHALT_PCA_Updates, join_attributes="ALL", cluster_tolerance="", output_type="INPUT")

# Process: Intersect (4)
arcpy.Intersect_analysis(in_features=r"'C:\Users\dstarr\OneDrive - Johnson, Mirmiran & Thompson\Projects\MDOT MPA\Python tool\DODB12(1).sde\MPA_USER.PCA_POLYGONS' #;C:\Users\temp\PCA_DATA.gdb\OTHER_PCA #", out_feature_class=OTHER_PCA_Updates, join_attributes="ALL", cluster_tolerance="", output_type="INPUT")

