# -*- coding: utf-8 -*-
"""Generated by ArcGIS ModelBuilder on: 2019-09-03 08:13:10
All ModelBuilder functionality may not be exported. Edits may be required for equivalency with the original model.
"""

import arcpy

# To allow overwriting the outputs change the overwrite option to true.
arcpy.env.overwriteOutput = False

# Local variables:
AREAS_PCA_Layer = "PCA_POLYGONS_Layer"
AREAS_PCA_Layer__3_ = AREAS_PCA_Layer
AREAS_PCA_Layer__4_ = AREAS_PCA_Layer__3_
AREAS_PCA_Layer__5_ = AREAS_PCA_Layer__3_
AREAS_PCA_Layer__6_ = AREAS_PCA_Layer__3_
AREAS_PCA_Layer__7_ = AREAS_PCA_Layer__3_
AREAS_PCA_Layer__8_ = AREAS_PCA_Layer__3_
PCA_POLYGONS_Layer = AREAS_PCA_Layer__4_

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(in_features="", out_layer=AREAS_PCA_Layer, where_clause="", workspace="", field_info="OBJECTID OBJECTID VISIBLE NONE;AREASQYD AREASQYD VISIBLE NONE;AREASQFT AREASQFT VISIBLE NONE;MATERIAL MATERIAL VISIBLE NONE;LOCATION LOCATION VISIBLE NONE;USE_ USE_ VISIBLE NONE;USE_CUST USE_CUST VISIBLE NONE;LEASED LEASED VISIBLE NONE;MAIN_RESP MAIN_RESP VISIBLE NONE;CONDITION CONDITION VISIBLE NONE;COND_DATE COND_DATE VISIBLE NONE;TYPE TYPE VISIBLE NONE;TERMINAL TERMINAL VISIBLE NONE;ASSETID ASSETID VISIBLE NONE;ASSESSOR ASSESSOR VISIBLE NONE;ASSESSMENT_COMMENTS ASSESSMENT_COMMENTS VISIBLE NONE;GLOBALID GLOBALID VISIBLE NONE;AREAACRES AREAACRES VISIBLE NONE;CREATED_USER CREATED_USER VISIBLE NONE;CREATED_DATE CREATED_DATE VISIBLE NONE;LAST_EDITED_USER LAST_EDITED_USER VISIBLE NONE;LAST_EDITED_DATE LAST_EDITED_DATE VISIBLE NONE;COND_LABEL COND_LABEL VISIBLE NONE;SHAPE SHAPE VISIBLE NONE;SHAPE.AREA SHAPE.AREA VISIBLE NONE;SHAPE.LEN SHAPE.LEN VISIBLE NONE")

# Process: Add Join
arcpy.AddJoin_management(in_layer_or_view=AREAS_PCA_Layer, in_field="ASSETID", join_table="AREAS_PCA_HISTORIC", join_field="ASSETID", join_type="KEEP_COMMON")

# Process: Conc Calc Date
arcpy.CalculateField_management(in_table=AREAS_PCA_Layer__3_, field="MPA_USER.PCA_POLYGONS.COND_DATE", expression="!CONCRETE_PCA_Updates.LAST_EDITED_DATE_1!", expression_type="PYTHON_9.3", code_block="")

# Process: Conc Calc Material
arcpy.CalculateField_management(in_table=AREAS_PCA_Layer__3_, field="MPA_USER.PCA_POLYGONS.MATERIAL", expression="!CONCRETE_PCA_Updates.MATERIAL_1!", expression_type="PYTHON_9.3", code_block="")

# Process: Conc Calc Assessment
arcpy.CalculateField_management(in_table=AREAS_PCA_Layer__3_, field="MPA_USER.PCA_POLYGONS.ASSESSMENT_COMMENTS", expression="!CONCRETE_PCA_Updates.ASSESSMENT_COMMENTS_1!", expression_type="PYTHON_9.3", code_block="")

# Process: Conc Calc Editor
arcpy.CalculateField_management(in_table=AREAS_PCA_Layer__3_, field="MPA_USER.PCA_POLYGONS.ASSESSOR", expression="!CONCRETE_PCA_Updates.LAST_EDITED_USER_1!", expression_type="PYTHON_9.3", code_block="")

# Process: Conc Calc Cond
arcpy.CalculateField_management(in_table=AREAS_PCA_Layer__3_, field="MPA_USER.PCA_POLYGONS.CONDITION", expression="!CONCRETE_PCA_Updates.CONDITION_1!", expression_type="PYTHON_9.3", code_block="")

# Process: Calculate Field (2)
arcpy.CalculateField_management(in_table=AREAS_PCA_Layer__4_, field="COND_LABEL", expression="Reclass(!MPA_USER.PCA_POLYGONS.CONDITION!)", expression_type="PYTHON3", code_block="def Reclass(field):
  if field == 5:
    return "Good"
  elif field == 4:
    return "Good" 
  elif field == 3:
    return "Fair"  
  elif field == 2:
    return "Poor"
  elif field == 1:
    return "Poor"")

